server:
  port : 8080
  error:
    include-stacktrace: ALWAYS



spring:
  security:
    enabled: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  datasource:
    url: jdbc:postgresql://localhost:5432/bookingplatform
    username: postgres
    password: postgres

    # default connection pool
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

    # drop n create table again, good for testing, comment this in production
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        type: INFO
    root:
      INFO